# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title
relative_permalinks: true

# Setup
title:               Michal Konturek
tagline:             'Creating awesome things with code.'
description:         'Michal Konturek on mobile development; mainly iOS , Objective-C, Swift, Cocoa and CocoaTouch.'
url:                 http://localhost:4000
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Michal Konturek
  url:               https://twitter.com/michalkonturek
  email:             michal.konturek@gmail.com
